apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dex
  namespace: ainur
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: ainur
  sources:
    - repoURL: https://charts.dexidp.io
      targetRevision: 0.19.0
      chart: dex
      helm:
        valueFiles:
          - $values/src/manifests/ainur/dex/values.yaml
    - repoURL: https://github.com/andrewiankidd/project-iluvatar.git
      targetRevision:  main
      path: src/manifests/ainur/dex
    - repoURL: https://github.com/andrewiankidd/project-iluvatar.git
      targetRevision:  main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: ainur-dex
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        ainur.kidd.network/ca: inject
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
