apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: headlamp
  namespace: ainur
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: ainur
  sources:
    - repoURL: https://kubernetes-sigs.github.io/headlamp/
      targetRevision: 0.36.0
      chart: headlamp
      helm:
        valueFiles:
          - $values/src/manifests/ainur/headlamp/values.yaml
    - repoURL: https://github.com/andrewiankidd/project-iluvatar.git
      targetRevision:  main
      ref: values
    - repoURL: https://github.com/andrewiankidd/project-iluvatar.git
      targetRevision:  main
      path: src/manifests/ainur/headlamp
  destination:
    server: https://kubernetes.default.svc
    namespace: ainur-headlamp
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        ainur.kidd.network/ca: inject
    automated:
      prune: true
      selfHeal: true
