apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pi-netboot
  namespace: ainur
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: ainur
  source:
    repoURL: https://github.com/andrewiankidd/project-iluvatar.git
    targetRevision:  main
    path: src/manifests/ainur/pi-netboot
  destination:
    server: https://kubernetes.default.svc
    namespace: ainur-netboot
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        ainur.kidd.network/ca: inject
    automated:
      prune: true
      selfHeal: true
