apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dex-ingress
  namespace: ainur-dex
  annotations:
    kubernetes.io/ingress.class: "traefik"
    cert-manager.io/cluster-issuer: "local-ca"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - dex.kidd.network
      secretName: dex-tls
  rules:
    - host: dex.kidd.network
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dex
                port:
                  number: 5556
