---
apiVersion: v1
kind: Service
metadata:
  name: omni-frontend
  namespace: ainur-sidero-omni
  labels:
    app.kubernetes.io/part-of: sidero-omni
    app.kubernetes.io/component: omni
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/component: omni
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: omni
  namespace: ainur-sidero-omni
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`omni.kidd.network`)
      kind: Rule
      services:
        - name: omni-frontend
          port: 80
          scheme: https
          serversTransport: omni-https
  tls:
    secretName: omni-tls
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: omni-kubernetes-proxy
  namespace: ainur-sidero-omni
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`omni.kubernetes.kidd.network`)
      kind: Rule
      services:
        - name: internal
          port: 8095
          scheme: https
          serversTransport: omni-https
  tls:
    secretName: omni-tls
