apiVersion: v1
kind: Secret
metadata:
  name: omnictl-config
  namespace: ainur-sidero-omni
type: Opaque
stringData:
  omniconfig.yaml: |
    contexts:
      default:
        url: https://omni.kidd.network/
        auth:
          siderov1:
            identity: omni@local
    context: default
