apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: omni-siderolink
  namespace: ainur-sidero-omni
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`omni.siderolink.kidd.network`)
      kind: Rule
      services:
        - name: internal
          port: 8090
          scheme: h2c
  tls:
    secretName: omni-tls
