apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: omni-siderolink
  namespace: ainur-sidero-omni
spec:
  entryPoints:
    - websecure
  routes:
    - match: HostSNI(`omni.siderolink.kidd.network`)
      services:
        - name: internal
          port: 8090
  tls:
    passthrough: true
