apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bootstrap-http
  namespace: ainur-netboot
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  ingressClassName: traefik
  rules:
    - host: bootstrap.kidd.network
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bootstrap-http
                port:
                  number: 80
