apiVersion: v1
kind: Service
metadata:
  name: bootstrap-http
  namespace: ainur-netboot
spec:
  type: ClusterIP
  selector:
    app: netboot
    component: http
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  externalIPs:
    - 192.168.1.59
