apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ainur-netboot
resources:
  - namespace.yaml
  - configmap.yaml
  - pvcs.yaml
  - tftp-deployment.yaml
  - nfs-deployment.yaml
  - http-deployment.yaml
  - http-service.yaml
  - http-ingress.yaml
  - builder-job.yaml
  - kube-vip.yaml
